const getSNAdata = async (simulationId) => {
  const res = {
    data: [
      {
        "Unnamed: 0": 0,
        communication_type: "",
        conversation_id: "",
        duration: 0.8100000000000023,
        end_time: 373.59,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 372.78,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 1,
        communication_type: "",
        conversation_id: "",
        duration: 0.4499999999999886,
        end_time: 377.34,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 376.89,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 2,
        communication_type: "",
        conversation_id: "",
        duration: 0.4200000000000159,
        end_time: 384.69,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 384.27,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 3,
        communication_type: "",
        conversation_id: "",
        duration: 1.3199999999999932,
        end_time: 393.39,
        initiator: "red",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 392.07,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 4,
        communication_type: "",
        conversation_id: "",
        duration: 0.9899999999999524,
        end_time: 402.96,
        initiator: "red",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 401.97,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 5,
        communication_type: "",
        conversation_id: "",
        duration: 3.569999999999993,
        end_time: 410.49,
        initiator: "red",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 406.92,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 6,
        communication_type: "",
        conversation_id: "",
        duration: 16.379999999999995,
        end_time: 430.11,
        initiator: "red",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 413.73,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 7,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000000136,
        end_time: 421.32,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 420.96,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 8,
        communication_type: "",
        conversation_id: "",
        duration: 40.10999999999996,
        end_time: 473.34,
        initiator: "red",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 433.23,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 9,
        communication_type: "",
        conversation_id: "",
        duration: 1.740000000000009,
        end_time: 474,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 472.26,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 10,
        communication_type: "",
        conversation_id: "",
        duration: 5.730000000000018,
        end_time: 482.88,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 477.15,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 11,
        communication_type: "",
        conversation_id: "",
        duration: 3.990000000000009,
        end_time: 494.79,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 490.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 12,
        communication_type: "",
        conversation_id: "",
        duration: 2.430000000000007,
        end_time: 500.79,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 498.36,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 13,
        communication_type: "",
        conversation_id: "",
        duration: 1.2900000000000205,
        end_time: 508.86,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 507.57,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 14,
        communication_type: "",
        conversation_id: "",
        duration: 6.599999999999909,
        end_time: 525.42,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 518.82,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 15,
        communication_type: "",
        conversation_id: "",
        duration: 0.5399999999999636,
        end_time: 529.86,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 529.32,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 16,
        communication_type: "",
        conversation_id: "",
        duration: 36.99000000000001,
        end_time: 566.79,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 529.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 17,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000000136,
        end_time: 541.92,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 541.56,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 18,
        communication_type: "",
        conversation_id: "",
        duration: 2.2799999999999727,
        end_time: 561.3,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 559.02,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 19,
        communication_type: "",
        conversation_id: "",
        duration: 7.3799999999999955,
        end_time: 570.99,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 563.61,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 20,
        communication_type: "",
        conversation_id: "",
        duration: 4.889999999999986,
        end_time: 570.27,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 565.38,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 21,
        communication_type: "",
        conversation_id: "",
        duration: 9.92999999999995,
        end_time: 579.87,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 569.94,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 22,
        communication_type: "",
        conversation_id: "",
        duration: 6.8700000000000045,
        end_time: 581.52,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 574.65,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 23,
        communication_type: "",
        conversation_id: "",
        duration: 1.5900000000000318,
        end_time: 581.46,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 579.87,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 24,
        communication_type: "",
        conversation_id: "",
        duration: 26.04000000000008,
        end_time: 609.57,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 583.53,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 25,
        communication_type: "",
        conversation_id: "",
        duration: 0.4799999999999045,
        end_time: 585.18,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 584.7,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 26,
        communication_type: "",
        conversation_id: "",
        duration: 2.339999999999918,
        end_time: 595.05,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 592.71,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 27,
        communication_type: "",
        conversation_id: "",
        duration: 1.5599999999999454,
        end_time: 600.66,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 599.1,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 28,
        communication_type: "",
        conversation_id: "",
        duration: 0.3299999999999272,
        end_time: 611.31,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 610.98,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 29,
        communication_type: "",
        conversation_id: "",
        duration: 33.989999999999895,
        end_time: 647.43,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 613.44,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 30,
        communication_type: "",
        conversation_id: "",
        duration: 0.6299999999999955,
        end_time: 633.18,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 632.55,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 31,
        communication_type: "",
        conversation_id: "",
        duration: 33.059999999999945,
        end_time: 674.31,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 641.25,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 32,
        communication_type: "",
        conversation_id: "",
        duration: 6.960000000000036,
        end_time: 659.76,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 652.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 33,
        communication_type: "",
        conversation_id: "",
        duration: 22.16999999999996,
        end_time: 685.53,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 663.36,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 34,
        communication_type: "",
        conversation_id: "",
        duration: 3.7799999999999727,
        end_time: 690.18,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 686.4,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 35,
        communication_type: "",
        conversation_id: "",
        duration: 17.93999999999994,
        end_time: 707.16,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 689.22,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 36,
        communication_type: "",
        conversation_id: "",
        duration: 2.5799999999999272,
        end_time: 707.04,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 704.46,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 37,
        communication_type: "",
        conversation_id: "",
        duration: 2.340000000000032,
        end_time: 713.01,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 710.67,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 38,
        communication_type: "",
        conversation_id: "",
        duration: 84.89999999999998,
        end_time: 795.99,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 711.09,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 39,
        communication_type: "",
        conversation_id: "",
        duration: 8.93999999999994,
        end_time: 726.18,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 717.24,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 40,
        communication_type: "",
        conversation_id: "",
        duration: 4.709999999999923,
        end_time: 742.05,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 737.34,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 41,
        communication_type: "",
        conversation_id: "",
        duration: 8.490000000000009,
        end_time: 754.5,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 746.01,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 42,
        communication_type: "",
        conversation_id: "",
        duration: 25.800000000000068,
        end_time: 784.47,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 758.67,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 43,
        communication_type: "",
        conversation_id: "",
        duration: 0.4499999999999318,
        end_time: 781.02,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 780.57,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 44,
        communication_type: "",
        conversation_id: "",
        duration: 13.979999999999905,
        end_time: 801.93,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 787.95,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 45,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000000136,
        end_time: 791.16,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 790.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 46,
        communication_type: "",
        conversation_id: "",
        duration: 67.76999999999998,
        end_time: 867.06,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 799.29,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 47,
        communication_type: "",
        conversation_id: "",
        duration: 9.33000000000004,
        end_time: 825.75,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 816.42,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 48,
        communication_type: "",
        conversation_id: "",
        duration: 14.309999999999944,
        end_time: 848.31,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 834,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 49,
        communication_type: "",
        conversation_id: "",
        duration: 0.4200000000000727,
        end_time: 857.46,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 857.04,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 50,
        communication_type: "",
        conversation_id: "",
        duration: 44.27999999999997,
        end_time: 907.05,
        initiator: "red",
        location: "",
        receiver: "yellow",
        stage_based_on_num_of_student: "",
        start_time: 862.77,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 51,
        communication_type: "",
        conversation_id: "",
        duration: 0.6600000000000819,
        end_time: 863.94,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 863.28,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 52,
        communication_type: "",
        conversation_id: "",
        duration: 0.4200000000000727,
        end_time: 867.09,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 866.67,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 53,
        communication_type: "",
        conversation_id: "",
        duration: 18.299999999999955,
        end_time: 888.3,
        initiator: "green",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 870,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 54,
        communication_type: "",
        conversation_id: "",
        duration: 42.77999999999997,
        end_time: 914.67,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 871.89,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 55,
        communication_type: "",
        conversation_id: "",
        duration: 1.4400000000000546,
        end_time: 875.1,
        initiator: "yellow",
        location: "",
        receiver: "green,red",
        stage_based_on_num_of_student: "",
        start_time: 873.66,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 56,
        communication_type: "",
        conversation_id: "",
        duration: 0.4799999999999045,
        end_time: 878.67,
        initiator: "yellow",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 878.19,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 57,
        communication_type: "",
        conversation_id: "",
        duration: 0.9300000000000636,
        end_time: 883.83,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 882.9,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 58,
        communication_type: "",
        conversation_id: "",
        duration: 0.4500000000000455,
        end_time: 888.36,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 887.91,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 59,
        communication_type: "",
        conversation_id: "",
        duration: 1.32000000000005,
        end_time: 892.83,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 891.51,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 60,
        communication_type: "",
        conversation_id: "",
        duration: 54.57000000000005,
        end_time: 947.58,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 893.01,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 61,
        communication_type: "",
        conversation_id: "",
        duration: 4.440000000000055,
        end_time: 904.32,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 899.88,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 62,
        communication_type: "",
        conversation_id: "",
        duration: 0.3300000000000409,
        end_time: 907.74,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 907.41,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 63,
        communication_type: "",
        conversation_id: "",
        duration: 44.31000000000006,
        end_time: 955.11,
        initiator: "red",
        location: "",
        receiver: "yellow",
        stage_based_on_num_of_student: "",
        start_time: 910.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 64,
        communication_type: "",
        conversation_id: "",
        duration: 1.8299999999999272,
        end_time: 914.31,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 912.48,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 65,
        communication_type: "",
        conversation_id: "",
        duration: 13.16999999999996,
        end_time: 931.14,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 917.97,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 66,
        communication_type: "",
        conversation_id: "",
        duration: 0.4199999999999591,
        end_time: 926.91,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 926.49,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 67,
        communication_type: "",
        conversation_id: "",
        duration: 3.870000000000005,
        end_time: 936.48,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 932.61,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 68,
        communication_type: "",
        conversation_id: "",
        duration: 43.860000000000014,
        end_time: 978.09,
        initiator: "blue",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 934.23,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 69,
        communication_type: "",
        conversation_id: "",
        duration: 0.6000000000000227,
        end_time: 948.03,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 947.43,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 70,
        communication_type: "",
        conversation_id: "",
        duration: 10.199999999999932,
        end_time: 961.56,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 951.36,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 71,
        communication_type: "",
        conversation_id: "",
        duration: 92.46000000000004,
        end_time: 1046.25,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 953.79,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 72,
        communication_type: "",
        conversation_id: "",
        duration: 6.149999999999977,
        end_time: 964.47,
        initiator: "red",
        location: "",
        receiver: "yellow",
        stage_based_on_num_of_student: "",
        start_time: 958.32,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 73,
        communication_type: "",
        conversation_id: "",
        duration: 34.91999999999996,
        end_time: 1003.38,
        initiator: "red",
        location: "",
        receiver: "yellow",
        stage_based_on_num_of_student: "",
        start_time: 968.46,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 74,
        communication_type: "",
        conversation_id: "",
        duration: 11.819999999999936,
        end_time: 982.41,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 970.59,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 75,
        communication_type: "",
        conversation_id: "",
        duration: 253.98,
        end_time: 1235.73,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 981.75,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 76,
        communication_type: "",
        conversation_id: "",
        duration: 0.9600000000000364,
        end_time: 987.27,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 986.31,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 77,
        communication_type: "",
        conversation_id: "",
        duration: 1.5,
        end_time: 994.59,
        initiator: "yellow",
        location: "",
        receiver: "relative,red",
        stage_based_on_num_of_student: "",
        start_time: 993.09,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 78,
        communication_type: "",
        conversation_id: "",
        duration: 0.3899999999999863,
        end_time: 996.84,
        initiator: "relative",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 996.45,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 79,
        communication_type: "",
        conversation_id: "",
        duration: 2.3700000000000045,
        end_time: 1004.52,
        initiator: "relative",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 1002.15,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 80,
        communication_type: "",
        conversation_id: "",
        duration: 3.8099999999999454,
        end_time: 1010.25,
        initiator: "red",
        location: "",
        receiver: "relative",
        stage_based_on_num_of_student: "",
        start_time: 1006.44,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 81,
        communication_type: "",
        conversation_id: "",
        duration: 7.230000000000018,
        end_time: 1019.97,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1012.74,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 82,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1013.88,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1013.58,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 83,
        communication_type: "",
        conversation_id: "",
        duration: 5.940000000000055,
        end_time: 1028.67,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1022.73,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 84,
        communication_type: "",
        conversation_id: "",
        duration: 0.4800000000000182,
        end_time: 1027.35,
        initiator: "yellow",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 1026.87,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 85,
        communication_type: "",
        conversation_id: "",
        duration: 16.440000000000055,
        end_time: 1047.75,
        initiator: "doctor",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1031.31,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 86,
        communication_type: "",
        conversation_id: "",
        duration: 1.5599999999999454,
        end_time: 1033.62,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1032.06,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 87,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1033.08,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1032.78,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 88,
        communication_type: "",
        conversation_id: "",
        duration: 3.599999999999909,
        end_time: 1045.53,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1041.93,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 89,
        communication_type: "",
        conversation_id: "",
        duration: 11.399999999999864,
        end_time: 1061.34,
        initiator: "green",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1049.94,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 90,
        communication_type: "",
        conversation_id: "",
        duration: 0.7799999999999727,
        end_time: 1053.72,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1052.94,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 91,
        communication_type: "",
        conversation_id: "",
        duration: 3.599999999999909,
        end_time: 1058.37,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1054.77,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 92,
        communication_type: "",
        conversation_id: "",
        duration: 3,
        end_time: 1063.02,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1060.02,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 93,
        communication_type: "",
        conversation_id: "",
        duration: 0.3299999999999272,
        end_time: 1070.76,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1070.43,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 94,
        communication_type: "",
        conversation_id: "",
        duration: 0.4500000000000455,
        end_time: 1072.47,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1072.02,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 95,
        communication_type: "",
        conversation_id: "",
        duration: 2.2200000000000277,
        end_time: 1077.9,
        initiator: "doctor",
        location: "",
        receiver: "green,blue",
        stage_based_on_num_of_student: "",
        start_time: 1075.68,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 96,
        communication_type: "",
        conversation_id: "",
        duration: 17.550000000000182,
        end_time: 1097.91,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1080.36,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 97,
        communication_type: "",
        conversation_id: "",
        duration: 0.3599999999998999,
        end_time: 1086.06,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1085.7,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 98,
        communication_type: "",
        conversation_id: "",
        duration: 11.309999999999944,
        end_time: 1105.23,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1093.92,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 99,
        communication_type: "",
        conversation_id: "",
        duration: 0.3899999999998726,
        end_time: 1098.57,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1098.18,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 100,
        communication_type: "",
        conversation_id: "",
        duration: 0.6900000000000546,
        end_time: 1102.65,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1101.96,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 101,
        communication_type: "",
        conversation_id: "",
        duration: 16.769999999999982,
        end_time: 1118.79,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1102.02,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 102,
        communication_type: "",
        conversation_id: "",
        duration: 3.240000000000009,
        end_time: 1113.63,
        initiator: "doctor",
        location: "",
        receiver: "yellow,blue",
        stage_based_on_num_of_student: "",
        start_time: 1110.39,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 103,
        communication_type: "",
        conversation_id: "",
        duration: 0.4500000000000455,
        end_time: 1113.9,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1113.45,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 104,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000001273,
        end_time: 1116.39,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1116.03,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 105,
        communication_type: "",
        conversation_id: "",
        duration: 11.669999999999844,
        end_time: 1133.58,
        initiator: "green",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1121.91,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 106,
        communication_type: "",
        conversation_id: "",
        duration: 0.3900000000001,
        end_time: 1122.69,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1122.3,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 107,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000001273,
        end_time: 1126.2,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1125.84,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 108,
        communication_type: "",
        conversation_id: "",
        duration: 0.7199999999997999,
        end_time: 1127.37,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1126.65,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 109,
        communication_type: "",
        conversation_id: "",
        duration: 1.410000000000082,
        end_time: 1137.27,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1135.86,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 110,
        communication_type: "",
        conversation_id: "",
        duration: 1.5,
        end_time: 1139.61,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1138.11,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 111,
        communication_type: "",
        conversation_id: "",
        duration: 44.49000000000001,
        end_time: 1184.79,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1140.3,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 112,
        communication_type: "",
        conversation_id: "",
        duration: 0.4800000000000182,
        end_time: 1141.2,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1140.72,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 113,
        communication_type: "",
        conversation_id: "",
        duration: 2.399999999999864,
        end_time: 1146.06,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1143.66,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 114,
        communication_type: "",
        conversation_id: "",
        duration: 0.5399999999999636,
        end_time: 1147.44,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1146.9,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 115,
        communication_type: "",
        conversation_id: "",
        duration: 0.3899999999998726,
        end_time: 1153.59,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1153.2,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 116,
        communication_type: "",
        conversation_id: "",
        duration: 3.060000000000173,
        end_time: 1156.41,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1153.35,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 117,
        communication_type: "",
        conversation_id: "",
        duration: 2.6699999999998454,
        end_time: 1166.58,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1163.91,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 118,
        communication_type: "",
        conversation_id: "",
        duration: 6.839999999999918,
        end_time: 1180.11,
        initiator: "doctor",
        location: "",
        receiver: "yellow,blue",
        stage_based_on_num_of_student: "",
        start_time: 1173.27,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 119,
        communication_type: "",
        conversation_id: "",
        duration: 0.3599999999998999,
        end_time: 1174.77,
        initiator: "yellow",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1174.41,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 120,
        communication_type: "",
        conversation_id: "",
        duration: 4.410000000000082,
        end_time: 1179.42,
        initiator: "red",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 1175.01,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 121,
        communication_type: "",
        conversation_id: "",
        duration: 0.75,
        end_time: 1180.11,
        initiator: "yellow",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1179.36,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 122,
        communication_type: "",
        conversation_id: "",
        duration: 0.3000000000001819,
        end_time: 1183.92,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1183.62,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 123,
        communication_type: "",
        conversation_id: "",
        duration: 6.720000000000027,
        end_time: 1190.79,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1184.07,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 124,
        communication_type: "",
        conversation_id: "",
        duration: 0.3299999999999272,
        end_time: 1186.74,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1186.41,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 125,
        communication_type: "",
        conversation_id: "",
        duration: 6.059999999999945,
        end_time: 1194.45,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1188.39,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 126,
        communication_type: "",
        conversation_id: "",
        duration: 9.420000000000073,
        end_time: 1199.7,
        initiator: "red",
        location: "",
        receiver: "relative",
        stage_based_on_num_of_student: "",
        start_time: 1190.28,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 127,
        communication_type: "",
        conversation_id: "",
        duration: 2.519999999999982,
        end_time: 1194.93,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1192.41,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 128,
        communication_type: "",
        conversation_id: "",
        duration: 2.399999999999864,
        end_time: 1196.79,
        initiator: "yellow",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 1194.39,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 129,
        communication_type: "",
        conversation_id: "",
        duration: 11.25,
        end_time: 1209.03,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1197.78,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 130,
        communication_type: "",
        conversation_id: "",
        duration: 0.959999999999809,
        end_time: 1200.84,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1199.88,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 131,
        communication_type: "",
        conversation_id: "",
        duration: 14.159999999999854,
        end_time: 1218.54,
        initiator: "red",
        location: "",
        receiver: "relative",
        stage_based_on_num_of_student: "",
        start_time: 1204.38,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 132,
        communication_type: "",
        conversation_id: "",
        duration: 0.4500000000000455,
        end_time: 1206.15,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1205.7,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 133,
        communication_type: "",
        conversation_id: "",
        duration: 16.8599999999999,
        end_time: 1227.57,
        initiator: "relative",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 1210.71,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 134,
        communication_type: "",
        conversation_id: "",
        duration: 9.569999999999936,
        end_time: 1223.82,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1214.25,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 135,
        communication_type: "",
        conversation_id: "",
        duration: 3.0299999999999727,
        end_time: 1217.49,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1214.46,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 136,
        communication_type: "",
        conversation_id: "",
        duration: 14.790000000000193,
        end_time: 1236.39,
        initiator: "red",
        location: "",
        receiver: "relative",
        stage_based_on_num_of_student: "",
        start_time: 1221.6,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 137,
        communication_type: "",
        conversation_id: "",
        duration: 10.650000000000093,
        end_time: 1240.2,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1229.55,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 138,
        communication_type: "",
        conversation_id: "",
        duration: 2.1299999999998818,
        end_time: 1234.02,
        initiator: "relative",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 1231.89,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 139,
        communication_type: "",
        conversation_id: "",
        duration: 6.720000000000027,
        end_time: 1240.83,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1234.11,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 140,
        communication_type: "",
        conversation_id: "",
        duration: 20.87999999999988,
        end_time: 1261.02,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1240.14,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 141,
        communication_type: "",
        conversation_id: "",
        duration: 14.309999999999944,
        end_time: 1257.51,
        initiator: "green",
        location: "",
        receiver: "yellow,doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1243.2,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 142,
        communication_type: "",
        conversation_id: "",
        duration: 4.559999999999945,
        end_time: 1248,
        initiator: "yellow",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1243.44,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 143,
        communication_type: "",
        conversation_id: "",
        duration: 0.8099999999999454,
        end_time: 1245.84,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1245.03,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 144,
        communication_type: "",
        conversation_id: "",
        duration: 0.5099999999999909,
        end_time: 1250.46,
        initiator: "doctor",
        location: "",
        receiver: "yellow,blue",
        stage_based_on_num_of_student: "",
        start_time: 1249.95,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 145,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1250.58,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1250.28,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 146,
        communication_type: "",
        conversation_id: "",
        duration: 4.259999999999991,
        end_time: 1257.75,
        initiator: "doctor",
        location: "",
        receiver: "green,yellow,blue",
        stage_based_on_num_of_student: "",
        start_time: 1253.49,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 147,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000001273,
        end_time: 1258.68,
        initiator: "yellow",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1258.32,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 148,
        communication_type: "",
        conversation_id: "",
        duration: 31.920000000000076,
        end_time: 1292.64,
        initiator: "green",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1260.72,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 149,
        communication_type: "",
        conversation_id: "",
        duration: 0.8399999999999181,
        end_time: 1264.59,
        initiator: "doctor",
        location: "",
        receiver: "green,blue",
        stage_based_on_num_of_student: "",
        start_time: 1263.75,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 150,
        communication_type: "",
        conversation_id: "",
        duration: 12.839999999999918,
        end_time: 1277.85,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1265.01,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 151,
        communication_type: "",
        conversation_id: "",
        duration: 0.4800000000000182,
        end_time: 1268.28,
        initiator: "doctor",
        location: "",
        receiver: "green,blue",
        stage_based_on_num_of_student: "",
        start_time: 1267.8,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 152,
        communication_type: "",
        conversation_id: "",
        duration: 55.76999999999998,
        end_time: 1332.15,
        initiator: "doctor",
        location: "",
        receiver: "green,blue",
        stage_based_on_num_of_student: "",
        start_time: 1276.38,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 153,
        communication_type: "",
        conversation_id: "",
        duration: 0.3000000000001819,
        end_time: 1278.39,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1278.09,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 154,
        communication_type: "",
        conversation_id: "",
        duration: 15.75,
        end_time: 1297.47,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1281.72,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 155,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1291.35,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1291.05,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 156,
        communication_type: "",
        conversation_id: "",
        duration: 3.6599999999998554,
        end_time: 1299.87,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1296.21,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 157,
        communication_type: "",
        conversation_id: "",
        duration: 4.980000000000018,
        end_time: 1302.06,
        initiator: "green",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1297.08,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 158,
        communication_type: "",
        conversation_id: "",
        duration: 0.6600000000000819,
        end_time: 1302.03,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1301.37,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 159,
        communication_type: "",
        conversation_id: "",
        duration: 86.57999999999993,
        end_time: 1391.82,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1305.24,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 160,
        communication_type: "",
        conversation_id: "",
        duration: 31.950000000000045,
        end_time: 1339.02,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1307.07,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 161,
        communication_type: "",
        conversation_id: "",
        duration: 8.13000000000011,
        end_time: 1329.75,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1321.62,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 162,
        communication_type: "",
        conversation_id: "",
        duration: 1.139999999999873,
        end_time: 1326.06,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1324.92,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 163,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1334.37,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1334.07,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 164,
        communication_type: "",
        conversation_id: "",
        duration: 2.369999999999891,
        end_time: 1337.82,
        initiator: "doctor",
        location: "",
        receiver: "yellow,blue",
        stage_based_on_num_of_student: "",
        start_time: 1335.45,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 165,
        communication_type: "",
        conversation_id: "",
        duration: 25.58999999999992,
        end_time: 1368,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1342.41,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 166,
        communication_type: "",
        conversation_id: "",
        duration: 0.599999999999909,
        end_time: 1344.24,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1343.64,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 167,
        communication_type: "",
        conversation_id: "",
        duration: 100.88999999999989,
        end_time: 1446.78,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1345.89,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 168,
        communication_type: "",
        conversation_id: "",
        duration: 0.4499999999998181,
        end_time: 1354.62,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1354.17,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 169,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1366.59,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1366.29,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 170,
        communication_type: "",
        conversation_id: "",
        duration: 0.4800000000000182,
        end_time: 1375.23,
        initiator: "red",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 1374.75,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 171,
        communication_type: "",
        conversation_id: "",
        duration: 14.819999999999936,
        end_time: 1391.25,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1376.43,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 172,
        communication_type: "",
        conversation_id: "",
        duration: 47.58000000000016,
        end_time: 1442.43,
        initiator: "green",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1394.85,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 173,
        communication_type: "",
        conversation_id: "",
        duration: 5.910000000000082,
        end_time: 1400.91,
        initiator: "blue",
        location: "",
        receiver: "green,doctor",
        stage_based_on_num_of_student: "",
        start_time: 1395,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 174,
        communication_type: "",
        conversation_id: "",
        duration: 0.6300000000001091,
        end_time: 1404.48,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1403.85,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 175,
        communication_type: "",
        conversation_id: "",
        duration: 51.12000000000012,
        end_time: 1455.9,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1404.78,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 176,
        communication_type: "",
        conversation_id: "",
        duration: 17.460000000000036,
        end_time: 1433.94,
        initiator: "red",
        location: "",
        receiver: "green",
        stage_based_on_num_of_student: "",
        start_time: 1416.48,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 177,
        communication_type: "",
        conversation_id: "",
        duration: 4.410000000000082,
        end_time: 1426.23,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1421.82,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 178,
        communication_type: "",
        conversation_id: "",
        duration: 0.3600000000001273,
        end_time: 1433.22,
        initiator: "yellow",
        location: "",
        receiver: "doctor,blue",
        stage_based_on_num_of_student: "",
        start_time: 1432.86,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 179,
        communication_type: "",
        conversation_id: "",
        duration: 0.900000000000091,
        end_time: 1439.01,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1438.11,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 180,
        communication_type: "",
        conversation_id: "",
        duration: 0.2999999999999545,
        end_time: 1439.37,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1439.07,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 181,
        communication_type: "",
        conversation_id: "",
        duration: 10.410000000000082,
        end_time: 1453.38,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1442.97,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 182,
        communication_type: "",
        conversation_id: "",
        duration: 0.3299999999999272,
        end_time: 1445.61,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1445.28,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 183,
        communication_type: "",
        conversation_id: "",
        duration: 30.029999999999973,
        end_time: 1478.16,
        initiator: "green",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1448.13,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 184,
        communication_type: "",
        conversation_id: "",
        duration: 12.420000000000073,
        end_time: 1462.92,
        initiator: "yellow",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1450.5,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 185,
        communication_type: "",
        conversation_id: "",
        duration: 19.25999999999999,
        end_time: 1473.03,
        initiator: "doctor",
        location: "",
        receiver: "blue",
        stage_based_on_num_of_student: "",
        start_time: 1453.77,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 186,
        communication_type: "",
        conversation_id: "",
        duration: 6.779999999999973,
        end_time: 1463.7,
        initiator: "red",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1456.92,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 187,
        communication_type: "",
        conversation_id: "",
        duration: 6.839999999999918,
        end_time: 1466.52,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1459.68,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 188,
        communication_type: "",
        conversation_id: "",
        duration: 8.6099999999999,
        end_time: 1474.74,
        initiator: "yellow",
        location: "",
        receiver: "red",
        stage_based_on_num_of_student: "",
        start_time: 1466.13,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 189,
        communication_type: "",
        conversation_id: "",
        duration: 5.159999999999855,
        end_time: 1476.09,
        initiator: "blue",
        location: "",
        receiver: "doctor",
        stage_based_on_num_of_student: "",
        start_time: 1470.93,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 190,
        communication_type: "",
        conversation_id: "",
        duration: 0.6000000000001364,
        end_time: 1471.68,
        initiator: "relative",
        location: "",
        receiver: "patient",
        stage_based_on_num_of_student: "",
        start_time: 1471.08,
        text: "",
        utterance_id: "",
      },
      {
        "Unnamed: 0": 191,
        communication_type: "",
        conversation_id: "",
        duration: 4.289999999999964,
        end_time: 1477.23,
        initiator: "red",
        location: "",
        receiver: "yellow",
        stage_based_on_num_of_student: "",
        start_time: 1472.94,
        text: "",
        utterance_id: "",
      },
    ],
    status: 200,
    statusText: "OK",
    headers: {
      "content-length": "47852",
      "content-type": "application/json",
    },
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false,
      },
      transformRequest: [null],
      transformResponse: [null],
      timeout: 0,
      xsrfCookieName: "XSRF-TOKEN",
      xsrfHeaderName: "X-XSRF-TOKEN",
      maxContentLength: -1,
      maxBodyLength: -1,
      env: {
        FormData: null,
      },
      headers: {
        "Access-Control-Allow-Origin": "http://localhost",
      },
      baseURL: "http://localhost:5003",
      method: "get",
      url: "/get_data?sessionId=416",
    },
    request: {},
  };

  return res;
};

const getENAdata = async (body) => {
  const { simulationId, startTime, endTime } = body;

  // Hard coded data
  const allResponse = `{
    "data": {
        "acknowledging": {
            "acknowledging": 0,
            "call-out": 82,
            "escalation": 16,
            "handover": 27,
            "questioning": 55,
            "task allocation": 80
        },
        "call-out": {
            "acknowledging": 82,
            "call-out": 0,
            "escalation": 12,
            "handover": 25,
            "questioning": 44,
            "task allocation": 65
        },
        "escalation": {
            "acknowledging": 16,
            "call-out": 12,
            "escalation": 0,
            "handover": 10,
            "questioning": 13,
            "task allocation": 13
        },
        "handover": {
            "acknowledging": 27,
            "call-out": 25,
            "escalation": 10,
            "handover": 0,
            "questioning": 19,
            "task allocation": 25
        },
        "questioning": {
            "acknowledging": 55,
            "call-out": 44,
            "escalation": 13,
            "handover": 19,
            "questioning": 0,
            "task allocation": 49
        },
        "task allocation": {
            "acknowledging": 80,
            "call-out": 65,
            "escalation": 13,
            "handover": 25,
            "questioning": 49,
            "task allocation": 0
        }
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "769",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_ena_data?sessionId=416&start=0&end=1486"
    },
    "request": {}
}`;
  const scnStartedResponse = `{
    "data": {
        "acknowledging": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "call-out": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "escalation": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "handover": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "questioning": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "task allocation": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        }
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "739",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_ena_data?sessionId=416&start=54&end=343"
    },
    "request": {}
}`;
  const handoverResponse = `{
    "data": {
        "acknowledging": {
            "acknowledging": 0,
            "call-out": 20,
            "escalation": 10,
            "handover": 12,
            "questioning": 20,
            "task allocation": 22
        },
        "call-out": {
            "acknowledging": 20,
            "call-out": 0,
            "escalation": 9,
            "handover": 12,
            "questioning": 18,
            "task allocation": 20
        },
        "escalation": {
            "acknowledging": 10,
            "call-out": 9,
            "escalation": 0,
            "handover": 7,
            "questioning": 9,
            "task allocation": 9
        },
        "handover": {
            "acknowledging": 12,
            "call-out": 12,
            "escalation": 7,
            "handover": 0,
            "questioning": 11,
            "task allocation": 12
        },
        "questioning": {
            "acknowledging": 20,
            "call-out": 18,
            "escalation": 9,
            "handover": 11,
            "questioning": 0,
            "task allocation": 20
        },
        "task allocation": {
            "acknowledging": 22,
            "call-out": 20,
            "escalation": 9,
            "handover": 12,
            "questioning": 20,
            "task allocation": 0
        }
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "761",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_ena_data?sessionId=416&start=343&end=849"
    },
    "request": {}
}`;
  const secondaryResponse = `{
    "data": {
        "acknowledging": {
            "acknowledging": 0,
            "call-out": 13,
            "escalation": 6,
            "handover": 4,
            "questioning": 8,
            "task allocation": 13
        },
        "call-out": {
            "acknowledging": 13,
            "call-out": 0,
            "escalation": 3,
            "handover": 4,
            "questioning": 7,
            "task allocation": 9
        },
        "escalation": {
            "acknowledging": 6,
            "call-out": 3,
            "escalation": 0,
            "handover": 3,
            "questioning": 4,
            "task allocation": 4
        },
        "handover": {
            "acknowledging": 4,
            "call-out": 4,
            "escalation": 3,
            "handover": 0,
            "questioning": 3,
            "task allocation": 2
        },
        "questioning": {
            "acknowledging": 8,
            "call-out": 7,
            "escalation": 4,
            "handover": 3,
            "questioning": 0,
            "task allocation": 6
        },
        "task allocation": {
            "acknowledging": 13,
            "call-out": 9,
            "escalation": 4,
            "handover": 2,
            "questioning": 6,
            "task allocation": 0
        }
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "743",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_ena_data?sessionId=416&start=849&end=1029"
    },
    "request": {}
}`;
  const doctorResponse = `{
    "data": {
        "acknowledging": {
            "acknowledging": 0,
            "call-out": 49,
            "escalation": 0,
            "handover": 11,
            "questioning": 27,
            "task allocation": 45
        },
        "call-out": {
            "acknowledging": 49,
            "call-out": 0,
            "escalation": 0,
            "handover": 9,
            "questioning": 19,
            "task allocation": 36
        },
        "escalation": {
            "acknowledging": 0,
            "call-out": 0,
            "escalation": 0,
            "handover": 0,
            "questioning": 0,
            "task allocation": 0
        },
        "handover": {
            "acknowledging": 11,
            "call-out": 9,
            "escalation": 0,
            "handover": 0,
            "questioning": 5,
            "task allocation": 11
        },
        "questioning": {
            "acknowledging": 27,
            "call-out": 19,
            "escalation": 0,
            "handover": 5,
            "questioning": 0,
            "task allocation": 23
        },
        "task allocation": {
            "acknowledging": 45,
            "call-out": 36,
            "escalation": 0,
            "handover": 11,
            "questioning": 23,
            "task allocation": 0
        }
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "755",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_ena_data?sessionId=416&start=1029&end=1486"
    },
    "request": {}
}`;
  let resResponse; // Declare resResponse outside the switch

  // Create a condition key for switch
  const conditionKey = `${simulationId}-${startTime}-${endTime}`;

  switch (conditionKey) {
    case "416-0-1486":
      resResponse = allResponse;
      break;
    case "416-54-343":
      resResponse = scnStartedResponse;
      break;
    case "416-343-849":
      resResponse = handoverResponse;
      break;
    case "416-849-1029":
      resResponse = secondaryResponse;
      break;
    case "416-1029-1486":
      resResponse = doctorResponse;
      break;
    default:
      resResponse = allResponse;
      break;
  }

  return JSON.parse(resResponse);
};

const getTeamworkBarchart = async (body) => {
  const { simulationId, startTime, endTime } = body;

  // Hard coded data
  const allResponse = `{
    "data": [
        {
            "label": [
                "Working together",
                "on tasks for Ruth"
            ],
            "value": 2.891367203634862
        },
        {
            "label": [
                "Working individually",
                "on tasks for Ruth"
            ],
            "value": 10.656753407682777
        },
        {
            "label": [
                "Working together",
                "on other tasks"
            ],
            "value": 2.41635687732342
        },
        {
            "label": [
                "Working individually",
                "on other tasks"
            ],
            "value": 12.598099958694755
        },
        {
            "label": [
                "Moving around",
                "the beds"
            ],
            "value": 71.4374225526642
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "377",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_teamwork_prio_data?sessionId=416&start=0&end=1486"
    },
    "request": {}
}`;
  const scnStartedResponse = `{
    "data": [
        {
            "label": [
                "Working together",
                "on tasks for Ruth"
            ],
            "value": 0
        },
        {
            "label": [
                "Working individually",
                "on tasks for Ruth"
            ],
            "value": 1.9653179190751449
        },
        {
            "label": [
                "Working together",
                "on other tasks"
            ],
            "value": 0
        },
        {
            "label": [
                "Working individually",
                "on other tasks"
            ],
            "value": 14.913294797687863
        },
        {
            "label": [
                "Moving around",
                "the beds"
            ],
            "value": 83.121387283237
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "349",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_teamwork_prio_data?sessionId=416&start=54&end=343"
    },
    "request": {}
}`;
  const handoverResponse = `{
    "data": [
        {
            "label": [
                "Working together",
                "on tasks for Ruth"
            ],
            "value": 0
        },
        {
            "label": [
                "Working individually",
                "on tasks for Ruth"
            ],
            "value": 8.783783783783786
        },
        {
            "label": [
                "Working together",
                "on other tasks"
            ],
            "value": 0
        },
        {
            "label": [
                "Working individually",
                "on other tasks"
            ],
            "value": 11.14864864864865
        },
        {
            "label": [
                "Moving around",
                "the beds"
            ],
            "value": 80.06756756756758
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "349",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_teamwork_prio_data?sessionId=416&start=343&end=849"
    },
    "request": {}
}`;
  const secondaryResponse = `{
    "data": [
        {
            "label": [
                "Working together",
                "on tasks for Ruth"
            ],
            "value": 2.8520499108734403
        },
        {
            "label": [
                "Working individually",
                "on tasks for Ruth"
            ],
            "value": 19.607843137254903
        },
        {
            "label": [
                "Working together",
                "on other tasks"
            ],
            "value": 18.894830659536545
        },
        {
            "label": [
                "Working individually",
                "on other tasks"
            ],
            "value": 6.951871657754011
        },
        {
            "label": [
                "Moving around",
                "the beds"
            ],
            "value": 51.69340463458111
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "380",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_teamwork_prio_data?sessionId=416&start=849&end=1029"
    },
    "request": {}
}`;
  const doctorResponse = `{
    "data": [
        {
            "label": [
                "Working together",
                "on tasks for Ruth"
            ],
            "value": 8.067664281067014
        },
        {
            "label": [
                "Working individually",
                "on tasks for Ruth"
            ],
            "value": 15.159401431359793
        },
        {
            "label": [
                "Working together",
                "on other tasks"
            ],
            "value": 0.715679895901106
        },
        {
            "label": [
                "Working individually",
                "on other tasks"
            ],
            "value": 15.029277813923226
        },
        {
            "label": [
                "Moving around",
                "the beds"
            ],
            "value": 61.02797657774885
        }
    ],
    "status": 200,
    "statusText": "OK",
    "headers": {
        "content-length": "379",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Access-Control-Allow-Origin": "http://localhost"
        },
        "baseURL": "http://localhost:5003",
        "method": "get",
        "url": "/get_teamwork_prio_data?sessionId=416&start=1029&end=1486"
    },
    "request": {}
}`;
  let resResponse; // Declare resResponse outside the switch

  // Create a condition key for switch
  const conditionKey = `${simulationId}-${startTime}-${endTime}`;

  switch (conditionKey) {
    case "416-0-1486":
      resResponse = allResponse;
      break;
    case "416-54-343":
      resResponse = scnStartedResponse;
      break;
    case "416-343-849":
      resResponse = handoverResponse;
      break;
    case "416-849-1029":
      resResponse = secondaryResponse;
      break;
    case "416-1029-1486":
      resResponse = doctorResponse;
      break;
    default:
      resResponse = allResponse;
      break;
  }

  return JSON.parse(resResponse);
};

export { getSNAdata, getENAdata, getTeamworkBarchart };
